NumPy is fast as it vectorises the code.This is called broadcasting.

In [1]:
import numpy as np

## Data Types and Attribute

NumPy's main data type is ndarray

<img src="numpy-anatomy-of-an-array-updated.png" alt="details of a numpy array" width =800/>

Key terms:
* **Array** - A list of numbers, can be multi-dimensional.
* **Scalar** - A single number (e.g. `7`).
* **Vector** - A list of numbers with 1-dimesion (e.g. `np.array([1, 2, 3])`).
* **Matrix** - A (usually) multi-deminsional list of numbers (e.g. `np.array([[1, 2, 3], [4, 5, 6]])`).

In [2]:
a1=np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([ [1,2.0,3.3] ,
                [4,5,6.5] ])
a3 = np.array([    [[1,2,3] , 
                   [4,5,6] ,
                   [7,8,9]    ] , 
              [ [10,11,12] , 
                [13,14,15] , 
                [16,17,18]    ]   ])

In [5]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [6]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [7]:
a1.shape

(3,)

In [8]:
a2.shape

(2, 3)

In [9]:
a3.shape

(2, 3, 3)

In [10]:
a1.ndim,a2.ndim,a3.ndim # numberof dimension

(1, 2, 3)

###### Here a1 is vector as it has only one dimension & a2 and a3 is are called matrix as it has more than one dimension

In [11]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [12]:
a1.size,a2.size,a3.size

(3, 6, 18)

In [13]:
type(a1),type(a2),type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

###### Create a DataFrame from a NumPy array

In [14]:
import pandas as pd

In [15]:
df=pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## Creating Arrays

In [16]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [17]:
sample_array.dtype

dtype('int32')

In [30]:
zeros = np.ones((3,3),dtype=int)
zeros

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [31]:
a =np.zeros((2,3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [32]:
a.dtype

dtype('float64')

In [33]:
type(a)

numpy.ndarray

In [34]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

###### np.random. 
    ==> randint       ==>random         ==>rand

In [35]:
random_array = np.random.randint(0, 10, size=(3,5))
random_array

array([[5, 4, 6, 6, 9],
       [4, 7, 8, 9, 1],
       [6, 8, 4, 8, 4]])

In [36]:
random_array.size

15

In [37]:
random_array.shape

(3, 5)

In [38]:
random_array_2 = np.random.random((5,3))

In [40]:
random_array_2

array([[0.84473393, 0.44388381, 0.84183809],
       [0.29300951, 0.10405648, 0.46141258],
       [0.93060593, 0.26625225, 0.66816349],
       [0.65680838, 0.63287188, 0.75981471],
       [0.59845996, 0.45584184, 0.97026394]])

In [41]:
random_array_2.shape

(5, 3)

In [42]:
random_array_3 = np.random.rand(5,3)
random_array_3

array([[0.45935209, 0.71985947, 0.08778508],
       [0.35128862, 0.08864371, 0.1215572 ],
       [0.68395583, 0.26409419, 0.57783832],
       [0.87116373, 0.0521808 , 0.7188424 ],
       [0.09759394, 0.69489981, 0.92074596]])

In [43]:
#Pseudo random numbers

In [50]:
np.random.seed(0)
random_array_4 = np.random.random((3,4))
random_array_4

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492]])

In [48]:
random_array_4 = np.random.random((3,4))
random_array_4

array([[0.61209572, 0.616934  , 0.94374808, 0.6818203 ],
       [0.3595079 , 0.43703195, 0.6976312 , 0.06022547],
       [0.66676672, 0.67063787, 0.21038256, 0.1289263 ]])

In [47]:
# Run above two tabs multiple time to see the difference
# when u run the 2nd tab for multiple times we get a new set of values but if we run the first tab for multiple times we get
# same values every time u run the code

## Viewing arrays and matrices

In [51]:
np.unique(random_array_4) # Gives onle unique values of an array

array([0.38344152, 0.4236548 , 0.43758721, 0.52889492, 0.54488318,
       0.5488135 , 0.60276338, 0.64589411, 0.71518937, 0.79172504,
       0.891773  , 0.96366276])

In [52]:
a1

array([1, 2, 3])

In [53]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [54]:
a1[0] , a1.shape

(1, (3,))

In [55]:
a2[0] , a2.shape

(array([1. , 2. , 3.3]), (2, 3))

In [56]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [57]:
a3.shape

(2, 3, 3)

In [58]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [79]:
a3[ 0:10 , 0:1 , 2:0:-1 ]

array([[[ 3,  2]],

       [[12, 11]]])

In [80]:
a3[::,::,::] #a3[1st dimension,rows,columns]

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [81]:
a5 = np.random.randint(10,size=(2,3,4,5,6))# In size last digit will be no of columns and last second number will be no of rows
a5                                      #inner most array will [1,1,7,9,0,9]

array([[[[[8, 1, 5, 9, 8, 9],
          [4, 3, 0, 3, 5, 0],
          [2, 3, 8, 1, 3, 3],
          [3, 7, 0, 1, 9, 9],
          [0, 4, 7, 3, 2, 7]],

         [[2, 0, 0, 4, 5, 5],
          [6, 8, 4, 1, 4, 9],
          [8, 1, 1, 7, 9, 9],
          [3, 6, 7, 2, 0, 3],
          [5, 9, 4, 4, 6, 4]],

         [[4, 3, 4, 4, 8, 4],
          [3, 7, 5, 5, 0, 1],
          [5, 9, 3, 0, 5, 0],
          [1, 2, 4, 2, 0, 3],
          [2, 0, 7, 5, 9, 0]],

         [[2, 7, 2, 9, 2, 3],
          [3, 2, 3, 4, 1, 2],
          [9, 1, 4, 6, 8, 2],
          [3, 0, 0, 6, 0, 6],
          [3, 3, 8, 8, 8, 2]]],


        [[[3, 2, 0, 8, 8, 3],
          [8, 2, 8, 4, 3, 0],
          [4, 3, 6, 9, 8, 0],
          [8, 5, 9, 0, 9, 6],
          [5, 3, 1, 8, 0, 4]],

         [[9, 6, 5, 7, 8, 8],
          [9, 2, 8, 6, 6, 9],
          [1, 6, 8, 8, 3, 2],
          [3, 6, 3, 6, 5, 7],
          [0, 8, 4, 6, 5, 8]],

         [[2, 3, 9, 7, 5, 3],
          [4, 5, 3, 3, 7, 9],
          [9, 9, 7, 3, 2, 

In [84]:
a4 = np.random.randint(10,size=(2,3,4,5))
a4

array([[[[4, 1, 8, 2, 3],
         [3, 4, 1, 6, 2],
         [5, 4, 9, 1, 5],
         [9, 4, 5, 7, 4]],

        [[4, 2, 2, 1, 3],
         [0, 1, 9, 1, 6],
         [9, 8, 6, 3, 0],
         [7, 3, 2, 5, 9]],

        [[7, 3, 4, 7, 6],
         [7, 3, 6, 9, 3],
         [7, 1, 3, 7, 8],
         [8, 4, 5, 3, 6]]],


       [[[9, 6, 2, 9, 3],
         [5, 7, 9, 0, 7],
         [1, 2, 5, 0, 5],
         [8, 9, 8, 2, 5]],

        [[3, 1, 7, 3, 8],
         [5, 5, 1, 9, 7],
         [2, 1, 0, 1, 0],
         [1, 1, 6, 8, 8]],

        [[3, 2, 0, 7, 4],
         [6, 0, 5, 3, 3],
         [9, 4, 9, 0, 6],
         [5, 3, 0, 0, 1]]]])

In [85]:
#first four numbers of inner most array
a4[:,:,:,:4]

array([[[[4, 1, 8, 2],
         [3, 4, 1, 6],
         [5, 4, 9, 1],
         [9, 4, 5, 7]],

        [[4, 2, 2, 1],
         [0, 1, 9, 1],
         [9, 8, 6, 3],
         [7, 3, 2, 5]],

        [[7, 3, 4, 7],
         [7, 3, 6, 9],
         [7, 1, 3, 7],
         [8, 4, 5, 3]]],


       [[[9, 6, 2, 9],
         [5, 7, 9, 0],
         [1, 2, 5, 0],
         [8, 9, 8, 2]],

        [[3, 1, 7, 3],
         [5, 5, 1, 9],
         [2, 1, 0, 1],
         [1, 1, 6, 8]],

        [[3, 2, 0, 7],
         [6, 0, 5, 3],
         [9, 4, 9, 0],
         [5, 3, 0, 0]]]])

## Manipulating & Computing Arrays

#### ==>Arithmetic

In [86]:
a1

array([1, 2, 3])

In [87]:
ones=np.ones(3)
ones

array([1., 1., 1.])

In [88]:
np.add(a1,ones)   ,     a1+ones # Both are same

(array([2., 3., 4.]), array([2., 3., 4.]))

In [89]:
a1-ones

array([0., 1., 2.])

In [90]:
a1

array([1, 2, 3])

In [91]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [92]:
a1*a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [93]:
a2//a1 ## Floor division removes the decimlas from the quotient(rounds down)

array([[1., 1., 1.],
       [4., 2., 2.]])

In [94]:
np.square(a2) , a2**2

(array([[ 1.  ,  4.  , 10.89],
        [16.  , 25.  , 42.25]]),
 array([[ 1.  ,  4.  , 10.89],
        [16.  , 25.  , 42.25]]))

In [95]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [96]:
b1=np.array([1,2,3,4])
b1

array([1, 2, 3, 4])

In [97]:
b2=np.reshape(a2 ,(6,1))
b2

array([[1. ],
       [2. ],
       [3.3],
       [4. ],
       [5. ],
       [6.5]])

b2*a3

ValueError: operands could not be broadcast together with shapes (6,1) (2,3,3)

In [98]:
# You are allowed to have one "unknown" dimension.
# Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.
# Pass -1 as the value, and NumPy will calculate this number for you.

### Aggregation
Performing same operation on a number of things

In [99]:
list_=[1,2,3] # python list
type(list_)

list

In [100]:
massive=np.random.random(10000)
massive.size

10000

In [105]:
#   sum() is a Python method   &   np.sum() is a NumPy method

In [106]:
#   %timeit is a magic function(has % before it)which is used to get time taken for execution

In [103]:
%timeit sum(massive) # Python method and NumPy array
%timeit sum(list_)   # Python method and Python list

729 µs ± 15.7 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
113 ns ± 2.61 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


In [104]:
%timeit np.sum(massive) # NumPy method and NumPy array
%timeit np.sum(list_)   # Numpy methos and Numpy array

7.18 µs ± 82.7 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
5.16 µs ± 193 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


###### Conclusion: - Use Python methods for Python datatypes and NumPy's methods for NumPy's dataframes for faster results

In [107]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [108]:
np.mean(a2), np.max(a2), np.min(a2) , np.sqrt(a2)

(3.6333333333333333,
 6.5,
 1.0,
 array([[1.        , 1.41421356, 1.81659021],
        [2.        , 2.23606798, 2.54950976]]))

In [ ]:
np.std(a2), np.var(a2)  # Higher variance ==>wide range of numbers  # standard devience is square root of Variance 

###### ==>  std and var

In [ ]:
high_var = np.array([1,100,200,300,4000,5000]) # 1-5000
low_var  = np.array([2,4,6,8,10])              # 2-10

In [ ]:
np.var(high_var), np.var(low_var)

In [ ]:
np.std(high_var), np.std(low_var)

In [ ]:
np.mean(high_var),np.mean(low_var)

In [ ]:
%matplotlib inline
import matplotlib.pyplot as plt
plt.hist(high_var)

In [ ]:
plt.hist(low_var)

## Reshaping and transposing

In [ ]:
a2,a2.shape

In [ ]:
a3

In [ ]:
a2.shape,a3.shape

a2*a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [ ]:
a2_reshaped = a2.reshape(2,3,1)
a2_reshaped

In [ ]:
a2_reshaped.shape , a3.shape

In [ ]:
a2_reshaped*a3

In [ ]:
3.3*7 # But in a2_reshaped * a3 it is shapped as 23.1

###### T - transpose method
filps the axis

In [ ]:
a3 , a3.T

In [ ]:
a3.shape,a3.T.shape

### Dot Product : - Matrix multiplication

In [ ]:
np.random.seed(0)
mat1 = np.random.randint(10,size=(5,3))
mat2 = np.random.randint(10,size=(5,3))
mat1,mat2

In [ ]:
# Element-wise multiplication (Hadamard Producr)
np.multiply(mat1,mat2) # or mat1*mat2 

np.dot(mat1,mat2)

ValueError: shapes (5,3) and (5,3) not aligned: 3 (dim 1) != 5 (dim 0)

In [ ]:
np.dot(mat1,mat2.T)

In [ ]:
## Exercise to multiply quantity matrix with price matrix to give total

In [ ]:
np.random.seed(2)
quantity = np.random.randint(10,size =( 4,3))
quantity

In [ ]:
weekly_quantity = pd.DataFrame(quantity,index=["mon","tue","wed","thu"],columns=["idly","dosa","vada"])
weekly_quantity,weekly_quantity.shape

In [ ]:
np.random.seed(0)
cost=np.random.randint(30,size=(3,1))
cost

In [ ]:
prices=np.array(weekly_quantity.dot(cost))
prices # 8*12 + 8*15 + 6*21 =342

In [ ]:
weekly_quantity["Total"] = prices
weekly_quantity

## Comparision Operators

In [ ]:
a1,a2

In [ ]:
bool_array= a1>=a2
bool_array

In [ ]:
type(bool_array),bool_array.dtype

In [ ]:
a1>5

## Sorting Arrays

In [ ]:
random_array = np.random.randint(10,size=(3,5))
random_array

In [ ]:
np.sort(random_array)#==>sorts the rows 

In [ ]:
np.argsort(random_array) #==>sorts the indexes of each array 

In [ ]:
a1

In [ ]:
np.argmin(a1),np.argmax(a1)

In [ ]:
random_array

In [ ]:
np.argmax(random_array,axis=0) # comparing each column. Ex:- in first column 6 is highest which has index number 2

In [ ]:
np.argmax(random_array,axis=1)# comparing each row

In [ ]:
a3

In [ ]:
a3[0][0][0]

###### ==>Axis in 3 dimensional array

In [ ]:
a4=np.random.randint(30,size=(2,3,3))
a4

In [ ]:
np.max(a4,axis=0) #comparing coresponding elements in twoarray with same index number 
                  # Ex:-first compares 6 and 21 then 23 and 12

In [ ]:
np.max(a4,axis=1)# comparing each column in 2 arrays
                 # Ex:-14 is max in 6,14,0

In [ ]:
np.max(a4,axis=2)# comparing each row
                #  Ex:-23 is max in 6,23,11

## NumPy in Real Life

<img src="panda.png" width = "100"/>

In [ ]:
# to get above image one must exexute following code in markdown:- """""  <img src="panda.png" width = "100"/>  """""

#### turn an image into a NumPy array

In [ ]:
from matplotlib.image import imread
panda = imread("panda.png")

In [ ]:
type(panda),panda.size,panda.shape,panda.ndim

In [ ]:
panda[:1] # pixel details